#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t intro2python \
                         -C "start_jupyter -T @tool -t intro2python.ipynb" \
                         -u anaconda-7 \
                         -r none \
                         -w headless
