#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t Intro2Python \
                         -C "start_jupyter -t -T @tool intro2python.ipynb" \
                         -u anaconda-7 -r none -w headless
